
package de.trispeedys.resourceplanning.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ResourceInfo", targetNamespace = "http://webservice.resourceplanning.trispeedys.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ResourceInfo {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns de.trispeedys.resourceplanning.webservice.HelperAssignmentDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public HelperAssignmentDTOArray queryHelperAssignments(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     */
    @WebMethod
    public void startSomeProcesses();

    /**
     * 
     */
    @WebMethod
    public void startOneProcesses();

    /**
     * 
     */
    @WebMethod
    public void sendAllMessages();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void processHelperCallback(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        HelperCallback arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void startHelperRequestProcess(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0,
        @WebParam(name = "arg1", partName = "arg1")
        long arg1);

    /**
     * 
     */
    @WebMethod
    public void startSomeProcessesWithNewHelpers();

}
