
package de.trispeedys.resourceplanning.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SomeTestServiceService", targetNamespace = "http://webservice.resourceplanning.trispeedys.de/", wsdlLocation = "http://localhost:8080/resourceplanning-bpm-0.0.1-SNAPSHOT/SomeTestServiceWs?wsdl")
public class SomeTestServiceService
    extends Service
{

    private final static URL SOMETESTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOMETESTSERVICESERVICE_EXCEPTION;
    private final static QName SOMETESTSERVICESERVICE_QNAME = new QName("http://webservice.resourceplanning.trispeedys.de/", "SomeTestServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/resourceplanning-bpm-0.0.1-SNAPSHOT/SomeTestServiceWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOMETESTSERVICESERVICE_WSDL_LOCATION = url;
        SOMETESTSERVICESERVICE_EXCEPTION = e;
    }

    public SomeTestServiceService() {
        super(__getWsdlLocation(), SOMETESTSERVICESERVICE_QNAME);
    }

    public SomeTestServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOMETESTSERVICESERVICE_QNAME, features);
    }

    public SomeTestServiceService(URL wsdlLocation) {
        super(wsdlLocation, SOMETESTSERVICESERVICE_QNAME);
    }

    public SomeTestServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOMETESTSERVICESERVICE_QNAME, features);
    }

    public SomeTestServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SomeTestServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SomeTestService
     */
    @WebEndpoint(name = "SomeTestServicePort")
    public SomeTestService getSomeTestServicePort() {
        return super.getPort(new QName("http://webservice.resourceplanning.trispeedys.de/", "SomeTestServicePort"), SomeTestService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SomeTestService
     */
    @WebEndpoint(name = "SomeTestServicePort")
    public SomeTestService getSomeTestServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.resourceplanning.trispeedys.de/", "SomeTestServicePort"), SomeTestService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOMETESTSERVICESERVICE_EXCEPTION!= null) {
            throw SOMETESTSERVICESERVICE_EXCEPTION;
        }
        return SOMETESTSERVICESERVICE_WSDL_LOCATION;
    }

}
