@startuml

class Helper {
	firstName::String
	lastName::String
}

class Event {
}

class Position {
    description::String
    minimalAge::int
}

class EventCommitment {
}

class EventPosition {
}

note left of EventPosition
	Zuordnung einer Position zu
	einem dedizierten Event
	(ergibt insgesamt eine M:N-Relation
	zwischen Position und Event)
end note

'---Verknüpfungen---

EventCommitment "1" -- "1" Helper

EventCommitment "1" -- "1" Event

EventCommitment "1" -- "1" Position

Position "1" -- "1" EventPosition
Event "1" -- "1" EventPosition

@enduml