@startuml

class Helper {
	firstName : String
	lastName : String
}

class Event {
	eventDate : Date
	eventKey : String
	description : String
}

class Position {
    description : String
    minimalAge : int
}

class EventCommitment {
	helper : Helper
	helperId : Long
	event : Event
	position : Position
}

class EventPosition {
	position : Position
	event : Event
}

note left of EventPosition
	Zuordnung einer Position zu
	einem dedizierten Event
	(ergibt insgesamt eine M:N-Relation
	zwischen Position und Event)
end note

class MessageQueue {
	fromAddress : String
	toAddress : String
	subject : String
	body : String
	messagingState : MessagingState
}

'---Verknüpfungen---

EventCommitment "1" -- "1" Helper

EventCommitment "1" -- "1" Event

EventCommitment "1" -- "1" Position

Position "1" -- "1" EventPosition
Event "1" -- "1" EventPosition

@enduml